// AUTOMATIC GENERATION : DO NOT MODIFY !
// Date : 2024-12-25T23:36:53.880Z
// List of files in ./src/modules/classic/blueprints

module.exports = {
  'ammo-arrow': require('./items/ammo/ammo-arrow.json'),
  'ammo-quarrel': require('./items/ammo/ammo-quarrel.json'),
  'arm-breast-plate': require('./items/armors/arm-breast-plate.json'),
  'arm-chain-mail': require('./items/armors/arm-chain-mail.json'),
  'arm-chain-shirt': require('./items/armors/arm-chain-shirt.json'),
  'arm-half-plate': require('./items/armors/arm-half-plate.json'),
  'arm-hide': require('./items/armors/arm-hide.json'),
  'arm-leather': require('./items/armors/arm-leather.json'),
  'arm-plate': require('./items/armors/arm-plate.json'),
  'arm-ring-mail': require('./items/armors/arm-ring-mail.json'),
  'arm-scale-mail': require('./items/armors/arm-scale-mail.json'),
  'arm-splint': require('./items/armors/arm-splint.json'),
  'arm-studded-leather': require('./items/armors/arm-studded-leather.json'),
  'tool-torch': require('./items/tools/tool-torch.json'),
  'wpn-battle-axe': require('./items/weapons/wpn-battle-axe.json'),
  'wpn-dagger': require('./items/weapons/wpn-dagger.json'),
  'wpn-great-axe': require('./items/weapons/wpn-great-axe.json'),
  'wpn-heavy-crossbow': require('./items/weapons/wpn-heavy-crossbow.json'),
  'wpn-light-crossbow': require('./items/weapons/wpn-light-crossbow.json'),
  'wpn-long-bow': require('./items/weapons/wpn-long-bow.json'),
  'wpn-long-sword': require('./items/weapons/wpn-long-sword.json'),
  'wpn-mace': require('./items/weapons/wpn-mace.json'),
  'wpn-quarterstaff': require('./items/weapons/wpn-quarterstaff.json'),
  'wpn-short-bow': require('./items/weapons/wpn-short-bow.json'),
  'wpn-short-spear': require('./items/weapons/wpn-short-spear.json'),
  'wpn-short-sword': require('./items/weapons/wpn-short-sword.json'),
  'ammo-type-arrow': require('./types/ammo-types/ammo-type-arrow.json'),
  'ammo-type-quarrel': require('./types/ammo-types/ammo-type-quarrel.json'),
  'arm-type-breast-plate': require('./types/armor-types/arm-type-breast-plate.json'),
  'arm-type-chain-mail': require('./types/armor-types/arm-type-chain-mail.json'),
  'arm-type-chain-shirt': require('./types/armor-types/arm-type-chain-shirt.json'),
  'arm-type-half-plate': require('./types/armor-types/arm-type-half-plate.json'),
  'arm-type-hide': require('./types/armor-types/arm-type-hide.json'),
  'arm-type-leather': require('./types/armor-types/arm-type-leather.json'),
  'arm-type-plate': require('./types/armor-types/arm-type-plate.json'),
  'arm-type-ring-mail': require('./types/armor-types/arm-type-ring-mail.json'),
  'arm-type-scale-mail': require('./types/armor-types/arm-type-scale-mail.json'),
  'arm-type-splint': require('./types/armor-types/arm-type-splint.json'),
  'arm-type-studded-leather': require('./types/armor-types/arm-type-studded-leather.json'),
  'gear-type-belt': require('./types/gear-types/gear-type-belt.json'),
  'gear-type-boots': require('./types/gear-types/gear-type-boots.json'),
  'gear-type-bracers': require('./types/gear-types/gear-type-bracers.json'),
  'gear-type-cloak': require('./types/gear-types/gear-type-cloak.json'),
  'gear-type-gauntlets': require('./types/gear-types/gear-type-gauntlets.json'),
  'gear-type-gloves': require('./types/gear-types/gear-type-gloves.json'),
  'gear-type-hat': require('./types/gear-types/gear-type-hat.json'),
  'gear-type-helm': require('./types/gear-types/gear-type-helm.json'),
  'gear-type-necklace': require('./types/gear-types/gear-type-necklace.json'),
  'gear-type-ring': require('./types/gear-types/gear-type-ring.json'),
  'wpn-type-battle-axe': require('./types/weapon-types/wpn-type-battle-axe.json'),
  'wpn-type-dagger': require('./types/weapon-types/wpn-type-dagger.json'),
  'wpn-type-great-axe': require('./types/weapon-types/wpn-type-great-axe.json'),
  'wpn-type-heavy-crossbow': require('./types/weapon-types/wpn-type-heavy-crossbow.json'),
  'wpn-type-light-crossbow': require('./types/weapon-types/wpn-type-light-crossbow.json'),
  'wpn-type-long-bow': require('./types/weapon-types/wpn-type-long-bow.json'),
  'wpn-type-long-sword': require('./types/weapon-types/wpn-type-long-sword.json'),
  'wpn-type-mace': require('./types/weapon-types/wpn-type-mace.json'),
  'wpn-type-quarterstaff': require('./types/weapon-types/wpn-type-quarterstaff.json'),
  'wpn-type-short-bow': require('./types/weapon-types/wpn-type-short-bow.json'),
  'wpn-type-short-spear': require('./types/weapon-types/wpn-type-short-spear.json'),
  'wpn-type-short-sword': require('./types/weapon-types/wpn-type-short-sword.json')
}
