// AUTOMATIC GENERATION : DO NOT MODIFY !
// Date : 2024-12-29T20:45:48.606Z
// List of files in ./src/store/getters

module.exports = {
  'getAbilities': require('./getAbilities.js'),
  'getAbilityBaseValues': require('./getAbilityBaseValues.js'),
  'getAbilityModifiers': require('./getAbilityModifiers.js'),
  'getActions': require('./getActions.js'),
  'getArmorClass': require('./getArmorClass.js'),
  'getAttackBonus': require('./getAttackBonus.js'),
  'getCapabilitySet': require('./getCapabilitySet.js'),
  'getConditionSet': require('./getConditionSet.js'),
  'getDamageMitigation': require('./getDamageMitigation.js'),
  'getDefensiveSlots': require('./getDefensiveSlots.js'),
  'getEffectRegistry': require('./getEffectRegistry.js'),
  'getEffectSet': require('./getEffectSet.js'),
  'getEffects': require('./getEffects.js'),
  'getEncumbrance': require('./getEncumbrance.js'),
  'getEnvironment': require('./getEnvironment.js'),
  'getEquipment': require('./getEquipment.js'),
  'getEquipmentProperties': require('./getEquipmentProperties.js'),
  'getHitPoints': require('./getHitPoints.js'),
  'getId': require('./getId.js'),
  'getImmunitySet': require('./getImmunitySet.js'),
  'getInnateProperties': require('./getInnateProperties.js'),
  'getLevel': require('./getLevel.js'),
  'getMaxHitPoints': require('./getMaxHitPoints.js'),
  'getMeleeAttackBonus': require('./getMeleeAttackBonus.js'),
  'getOffensiveSlots': require('./getOffensiveSlots.js'),
  'getProficiencyBonus': require('./getProficiencyBonus.js'),
  'getProficiencySet': require('./getProficiencySet.js'),
  'getProperties': require('./getProperties.js'),
  'getPropertySet': require('./getPropertySet.js'),
  'getRangedAttackBonus': require('./getRangedAttackBonus.js'),
  'getSavingThrowBonus': require('./getSavingThrowBonus.js'),
  'getSelectedOffensiveSlot': require('./getSelectedOffensiveSlot.js'),
  'getSelectedWeapon': require('./getSelectedWeapon.js'),
  'getSelectedWeaponAttributeSet': require('./getSelectedWeaponAttributeSet.js'),
  'getSlotProperties': require('./getSlotProperties.js'),
  'getSpeed': require('./getSpeed.js'),
  'getSpellDifficultyClass': require('./getSpellDifficultyClass.js'),
  'getWeaponRanges': require('./getWeaponRanges.js'),
  'isDead': require('./isDead.js'),
  'isEquipmentProficient': require('./isEquipmentProficient.js'),
  'isRangedWeaponLoaded': require('./isRangedWeaponLoaded.js'),
  'isWieldingShield': require('./isWieldingShield.js'),
  'isWieldingTwoHandedWeapon': require('./isWieldingTwoHandedWeapon.js')
}
