// AUTOMATIC GENERATION : DO NOT MODIFY !
// Date : 2025-08-12T23:20:42.437Z
// List of files in ./src/store/getters

module.exports = {
    'getAbilities': require('./getAbilities.js'),
    'getAbilityBaseValues': require('./getAbilityBaseValues.js'),
    'getAbilityModifiers': require('./getAbilityModifiers.js'),
    'getActions': require('./getActions.js'),
    'getActiveProperties': require('./getActiveProperties.js'),
    'getArmorClass': require('./getArmorClass.js'),
    'getAttackAbility': require('./getAttackAbility.js'),
    'getAttackBonus': require('./getAttackBonus.js'),
    'getCapabilitySet': require('./getCapabilitySet.js'),
    'getClassType': require('./getClassType.js'),
    'getConditionSet': require('./getConditionSet.js'),
    'getDamageMitigation': require('./getDamageMitigation.js'),
    'getDeadEffects': require('./getDeadEffects.js'),
    'getDefensiveSlots': require('./getDefensiveSlots.js'),
    'getEffectRegistry': require('./getEffectRegistry.js'),
    'getEffectSet': require('./getEffectSet.js'),
    'getEffectTagSet': require('./getEffectTagSet.js'),
    'getEffects': require('./getEffects.js'),
    'getEncumbrance': require('./getEncumbrance.js'),
    'getEnvironments': require('./getEnvironments.js'),
    'getEquipment': require('./getEquipment.js'),
    'getEquipmentProperties': require('./getEquipmentProperties.js'),
    'getHitPoints': require('./getHitPoints.js'),
    'getId': require('./getId.js'),
    'getImmunitySet': require('./getImmunitySet.js'),
    'getInnateProperties': require('./getInnateProperties.js'),
    'getLevel': require('./getLevel.js'),
    'getMaxHitPoints': require('./getMaxHitPoints.js'),
    'getMaxPreparedSpellCount': require('./getMaxPreparedSpellCount.js'),
    'getMeleeAttackBonus': require('./getMeleeAttackBonus.js'),
    'getOffensiveSlots': require('./getOffensiveSlots.js'),
    'getPoolValues': require('./getPoolValues.js'),
    'getProficiencyBonus': require('./getProficiencyBonus.js'),
    'getProficiencySet': require('./getProficiencySet.js'),
    'getProperties': require('./getProperties.js'),
    'getPropertySet': require('./getPropertySet.js'),
    'getRangedAttackBonus': require('./getRangedAttackBonus.js'),
    'getSavingThrowBonus': require('./getSavingThrowBonus.js'),
    'getSelectedOffensiveSlot': require('./getSelectedOffensiveSlot.js'),
    'getSelectedWeapon': require('./getSelectedWeapon.js'),
    'getSelectedWeaponAttributeSet': require('./getSelectedWeaponAttributeSet.js'),
    'getSkillValues': require('./getSkillValues.js'),
    'getSlotProperties': require('./getSlotProperties.js'),
    'getSpecie': require('./getSpecie.js'),
    'getSpecieProtectionSet': require('./getSpecieProtectionSet.js'),
    'getSpeed': require('./getSpeed.js'),
    'getSpellCastingAbility': require('./getSpellCastingAbility.js'),
    'getSpellDifficultyClass': require('./getSpellDifficultyClass.js'),
    'getSpellSet': require('./getSpellSet.js'),
    'getSpellSlots': require('./getSpellSlots.js'),
    'getUnmodifiedLevel': require('./getUnmodifiedLevel.js'),
    'getVariables': require('./getVariables.js'),
    'getWeaponRanges': require('./getWeaponRanges.js'),
    'hasSpellSlotCoolingDown': require('./hasSpellSlotCoolingDown.js'),
    'isDead': require('./isDead.js'),
    'isEquipmentProficient': require('./isEquipmentProficient.js'),
    'isRangedWeaponLoaded': require('./isRangedWeaponLoaded.js'),
    'isWieldingShield': require('./isWieldingShield.js'),
    'isWieldingTwoHandedWeapon': require('./isWieldingTwoHandedWeapon.js')
};
