// AUTOMATIC GENERATION : DO NOT MODIFY !
// Date : 2025-08-08T15:12:28.025Z
// List of files in ./src/consts

module.exports = {
    ...require('./abilities.json'),
    ...require('./action-failure-reasons.json'),
    ...require('./advantages-disadvantages.js'),
    ...require('./attack-failures.json'),
    ...require('./attack-types.json'),
    ...require('./capabilities.json'),
    ...require('./caster-types.json'),
    ...require('./casting-times.json'),
    ...require('./combat-action-type.json'),
    ...require('./combat-specials-events.json'),
    ...require('./conditions.json'),
    ...require('./creature-visibility.json'),
    ...require('./damage-types.json'),
    ...require('./effect-subtypes.json'),
    ...require('./effects.js'),
    ...require('./entity-types.json'),
    ...require('./environments.json'),
    ...require('./equipment-slots.json'),
    ...require('./events.json'),
    ...require('./genders.json'),
    ...require('./immunities.json'),
    ...require('./item-types.json'),
    ...require('./on-attack-hit.json'),
    ...require('./pool-variables.json'),
    ...require('./proficiencies.json'),
    ...require('./properties.js'),
    ...require('./races.json'),
    ...require('./roll-types.json'),
    ...require('./skill-proficiencies.json'),
    ...require('./species.json'),
    ...require('./spell-cast-target-types.json'),
    ...require('./threat-types.json'),
    ...require('./weapon-attributes.json'),
    ...require('./weapon-sizes.json')
};
