// AUTOMATIC GENERATION : DO NOT MODIFY !
// Date : 2024-11-25T19:05:10.470Z
// List of files in ./src/properties

module.exports = {
  "PROPERTY_ABILITY_MODIFIER": "PROPERTY_ABILITY_MODIFIER",
  "PROPERTY_ARMOR_CLASS_MODIFIER": "PROPERTY_ARMOR_CLASS_MODIFIER",
  "PROPERTY_ATTACK_COUNT_MODIFIER": "PROPERTY_ATTACK_COUNT_MODIFIER",
  "PROPERTY_ATTACK_MODIFIER": "PROPERTY_ATTACK_MODIFIER",
  "PROPERTY_CURSED": "PROPERTY_CURSED",
  "PROPERTY_DAMAGE_IMMUNITY": "PROPERTY_DAMAGE_IMMUNITY",
  "PROPERTY_DAMAGE_MODIFIER": "PROPERTY_DAMAGE_MODIFIER",
  "PROPERTY_DAMAGE_REDUCTION": "PROPERTY_DAMAGE_REDUCTION",
  "PROPERTY_DAMAGE_RESISTANCE": "PROPERTY_DAMAGE_RESISTANCE",
  "PROPERTY_DAMAGE_VULNERABILITY": "PROPERTY_DAMAGE_VULNERABILITY",
  "PROPERTY_DARKVISION": "PROPERTY_DARKVISION",
  "PROPERTY_EXTRA_HITPOINTS": "PROPERTY_EXTRA_HITPOINTS",
  "PROPERTY_HEALING_FACTOR": "PROPERTY_HEALING_FACTOR",
  "PROPERTY_HEALING_MODIFIER": "PROPERTY_HEALING_MODIFIER",
  "PROPERTY_IMMUNITY": "PROPERTY_IMMUNITY",
  "PROPERTY_LIGHT": "PROPERTY_LIGHT",
  "PROPERTY_REGENERATION": "PROPERTY_REGENERATION",
  "PROPERTY_SAVING_THROW_MODIFIER": "PROPERTY_SAVING_THROW_MODIFIER",
  "PROPERTY_SPEED_FACTOR": "PROPERTY_SPEED_FACTOR",
  "PROPERTY_UNIDENTIFIED": "PROPERTY_UNIDENTIFIED",
  "PROPERTY_WEIGHT_FACTOR": "PROPERTY_WEIGHT_FACTOR"
}
