// AUTOMATIC GENERATION : DO NOT MODIFY !
// Date : 2025-07-20T15:51:07.950Z
// List of files in ./src/properties

module.exports = {
    'PROPERTY_ABILITY_MODIFIER': require('./ability-modifier.js'),
    'PROPERTY_ADVANTAGE_ATTACK': require('./advantage-attack.js'),
    'PROPERTY_ADVANTAGE_SAVING_THROW': require('./advantage-saving-throw.js'),
    'PROPERTY_ARMOR_CLASS_MODIFIER': require('./armor-class-modifier.js'),
    'PROPERTY_ATTACK_COUNT_MODIFIER': require('./attack-count-modifier.js'),
    'PROPERTY_ATTACK_MODIFIER': require('./attack-modifier.js'),
    'PROPERTY_CRITICAL_RANGE_MODIFIER': require('./critical-range-modifier.js'),
    'PROPERTY_CURSED': require('./cursed.js'),
    'PROPERTY_DAMAGE_IMMUNITY': require('./damage-immunity.js'),
    'PROPERTY_DAMAGE_MODIFIER': require('./damage-modifier.js'),
    'PROPERTY_DAMAGE_REDUCTION': require('./damage-reduction.js'),
    'PROPERTY_DAMAGE_RESISTANCE': require('./damage-resistance.js'),
    'PROPERTY_DAMAGE_VULNERABILITY': require('./damage-vulnerability.js'),
    'PROPERTY_DARKVISION': require('./darkvision.js'),
    'PROPERTY_DISADVANTAGE_ATTACK': require('./disadvantage-attack.js'),
    'PROPERTY_DISADVANTAGE_SAVING_THROW': require('./disadvantage-saving-throw.js'),
    'PROPERTY_EXTRA_HITPOINTS': require('./extra-hitpoints.js'),
    'PROPERTY_EXTRA_WEAPON_DAMAGE_TYPE': require('./extra-weapon-damage-type.js'),
    'PROPERTY_FEAT': require('./feat.js'),
    'PROPERTY_HEALING_FACTOR': require('./healing-factor.js'),
    'PROPERTY_HEALING_MODIFIER': require('./healing-modifier.js'),
    'PROPERTY_IMMUNITY': require('./immunity.js'),
    'PROPERTY_LIGHT': require('./light.js'),
    'PROPERTY_MAX_DEXTERITY_BONUS': require('./max-dexterity-bonus.js'),
    'PROPERTY_MULTI_ATTACK': require('./multi-attack.js'),
    'PROPERTY_ON_ATTACK_HIT': require('./on-attack-hit.js'),
    'PROPERTY_REGENERATION': require('./regeneration.js'),
    'PROPERTY_SAVING_THROW_MODIFIER': require('./saving-throw-modifier.js'),
    'PROPERTY_SKILL_MODIFIER': require('./skill-modifier.js'),
    'PROPERTY_SNEAK_ATTACK': require('./sneak-attack.js'),
    'PROPERTY_SPECIAL_BEHAVIOR': require('./special-behavior.js'),
    'PROPERTY_SPEED_FACTOR': require('./speed-factor.js'),
    'PROPERTY_SPELL_POWER': require('./spell-power.js'),
    'PROPERTY_SPIKE_DAMAGE': require('./spike-damage.js'),
    'PROPERTY_THINKER': require('./thinker.js'),
    'PROPERTY_UNIDENTIFIED': require('./unidentified.js'),
    'PROPERTY_VAMPYRE': require('./vampyre.js'),
    'PROPERTY_WEIGHT_FACTOR': require('./weight-factor.js')
};
