// AUTOMATIC GENERATION : DO NOT MODIFY !
// Date : 2025-05-13T13:05:55.627Z
// List of files in ./src/effects

module.exports = {
    'EFFECT_ABILITY_MODIFIER': require('./ability-modifier.js'),
    'EFFECT_ADVANTAGE_ATTACK': require('./advantage-attack.js'),
    'EFFECT_ADVANTAGE_SAVING_THROW': require('./advantage-saving-throw.js'),
    'EFFECT_ARMOR_CLASS_MODIFIER': require('./armor-class-modifier.js'),
    'EFFECT_ATTACK_COUNT_MODIFIER': require('./attack-count-modifier.js'),
    'EFFECT_ATTACK_MODIFIER': require('./attack-modifier.js'),
    'EFFECT_BLINDNESS': require('./blindness.js'),
    'EFFECT_CHARM': require('./charm.js'),
    'EFFECT_DAMAGE_IMMUNITY': require('./damage-immunity.js'),
    'EFFECT_DAMAGE_MODIFIER': require('./damage-modifier.js'),
    'EFFECT_DAMAGE_REDUCTION': require('./damage-reduction.js'),
    'EFFECT_DAMAGE_RESISTANCE': require('./damage-resistance.js'),
    'EFFECT_DAMAGE_VULNERABILITY': require('./damage-vulnerability.js'),
    'EFFECT_DAMAGE': require('./damage.js'),
    'EFFECT_DARKVISION': require('./darkvision.js'),
    'EFFECT_DEATH': require('./death.js'),
    'EFFECT_DISADVANTAGE_ATTACK': require('./disadvantage-attack.js'),
    'EFFECT_DISADVANTAGE_SAVING_THROW': require('./disadvantage-saving-throw.js'),
    'EFFECT_DISEASE': require('./disease.js'),
    'EFFECT_FEAR': require('./fear.js'),
    'EFFECT_FLAG': require('./flag.js'),
    'EFFECT_HEAL': require('./heal.js'),
    'EFFECT_HEALING_FACTOR': require('./healing-factor.js'),
    'EFFECT_IMMUNITY': require('./immunity.js'),
    'EFFECT_INVISIBILITY': require('./invisibility.js'),
    'EFFECT_LIGHT': require('./light.js'),
    'EFFECT_NEGATIVE_LEVEL': require('./negative-level.js'),
    'EFFECT_PARALYSIS': require('./paralysis.js'),
    'EFFECT_PETRIFICATION': require('./petrification.js'),
    'EFFECT_REGENERATION': require('./regeneration.js'),
    'EFFECT_SAVING_THROW_MODIFIER': require('./saving-throw-modifier.js'),
    'EFFECT_SEE_INVISIBILITY': require('./see-invisibility.js'),
    'EFFECT_SKILL_MODIFIER': require('./skill-modifier.js'),
    'EFFECT_SPEED_FACTOR': require('./speed-factor.js'),
    'EFFECT_SPELL_POWER': require('./spell-power.js'),
    'EFFECT_SPIKE_DAMAGE': require('./spike-damage.js'),
    'EFFECT_STEALTH': require('./stealth.js'),
    'EFFECT_STUN': require('./stun.js')
};
